version: '3.4'

services:
  catalogdb:
    image: postgres
    networks:
      - bazarche_network

  pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - bazarche_network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    networks:
      - bazarche_network

  mediadb:
    image: mongo:latest
    networks:
      - bazarche_network

  mongo-express:
    image: mongo-express:latest
    networks:
      - bazarche_network

  catalog.api:
    container_name: catalogapi
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/BazarChe.Catalog/Catalog.Api/Dockerfile
    volumes:
      - ../BuildingBlocks/EventBus.Message/Options:/app/Options
    networks:
      - bazarche_network

  media.api:
    container_name: mediaapi
    image: ${DOCKER_REGISTRY-}mediaapi
    build:
      context: .
      dockerfile: Services/BazarChe.Media/Media.Api/Dockerfile
    volumes:
      - ../BuildingBlocks/EventBus.Message/Options:/app/Options
    networks:
      - bazarche_network

networks:
  bazarche_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
