version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data/

  minio:
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest   # تنظیمات کاربر پیش‌فرض
      RABBITMQ_DEFAULT_PASS: guest 

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10001:8080"
    depends_on:
      - catalogdb

  media.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10002:8080"